### ISSUE TITLE
添付ファイルのコンテンツが長いと厳しい

### ISSUE THREAD

**Issue by mattn** [vim-jp/slacklog-generator#127]
See https://vim-jp.org/slacklog/CSM0YPD0B/2020/03/#ts-1584927147.030000

折りたたむ？

**Comment by koron** [comment]
いま直接埋め込んでるけど、
JS側で動的に読み込むという手も考えられます。

generator 的にもそのほうがありがたくはあります。

**Comment by koron** [comment]
もしくは max-height キメて overflow: scroll か…

**Comment by koron** [comment]
`<pre>` に `max-height: 20vh` 設定したらこうなる。

![image](https://user-images.githubusercontent.com/468368/82133988-4104b800-982d-11ea-9f74-b8c8c42198fc.png)

**Comment by koron** [comment]
CSSにこれ追加すると、初期はビューポートの高さ 15%、リサイズ可能で最大 80% という感じになる。

いまはこのくらいが妥当かもしれない。

```css
pre[class*="language-"] {
    resize: vertical;
    min-height: 15vh;
    max-height: 80vh;
    height: 15vh;
}
```

@heavenshell どうでしょか?
